# Site settings
title: OmniOS Community Edition
description: illumos based server OS with ZFS, KVM and Linux zone support
url: "http://www.omniosce.org"
baseurl: ""
logo: OmniOS Community Edition
paginate: 5
paginate_path: "/page:num/"
omnios_stable: r151022
owner:
    email: info@omniosce.org
    facebook:
        show: true
        name: "OmniOS Community Edition"
        url: "https://fb.me/omniosce"
    github:
        show: true
        username: "omniosorg"
    twitter:
        show: true
        username: "omniosce"
    disqus:
        show: false
        username: "ichihararifa"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed

collections:
    docs:
        output: true
        permalink: /:path

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: page
      order: 999

permalink: "/article/:title"
gems:
    - jekyll-feed
