# Site settings
title: OmniOS Community Edition
description: illumos based server OS with ZFS, Bhyve, DTrace, Crossbow, SMF and Linux zone support
url: "https://omnios.org"
baseurl: ""
logo: OmniOS Community Edition
paginate: 12
paginate_path: "/news/page:num/"
download_path: https://downloads.omnios.org/media
uswest_path: https://us-west.mirror.omnios.org/downloads/media
download_prefix: omnios-
omnios_stable_date: the 3rd of November, 2025
omnios_stable: r151056
omnios_stable_suffix:
omnios_oldstable: r151052
omnios_lts_date: the 5th of May, 2025
omnios_lts: r151054
omnios_lts_suffix: r
omnios_bloody: 20251111
owner:
    email: info@omnios.org
    facebook:
        show: true
        name: "OmniOS Community Edition"
        url: "https://fb.me/omniosce"
    github:
        show: true
        username: "omniosorg"
    twitter:
        show: true
        username: "omniosce"
    disqus:
        show: false
        username: "ichihararifa"
    linkedin:
        show: false
        profile: "https://linkedin.com/in/your-profile-id-here"
sass:
    sass_dir: _sass
    style: compressed

collections:
    docs:
        output: true
        permalink: /:path

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: page
      order: 999

permalink: "/article/:title"

#exclude:
#  - /vendor/bundle/ruby/2.4.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb

markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-paginate

